### ISSUE TITLE
Verbosity feature request

### ISSUE THREAD

**Issue by TonyPuryer** [FredrikM97/Transmission-DH#1]
I'm running this via cron at 2am and do not see the output. The saved log file says "localhost:9091/transmission/rpc/ responded: "success" when a torrent is removed. Would it be possible for the output to include the torrent name that was removed?

Many thanks for this useful script.

Tony.

**Comment by FredrikM97** [comment]
There is no message displaying: Removing randomMovie [720p].mkv within the text file (if not check file permissions) ? 

How is the cronjob setup? 

There is currently no feature that prints content to console since everything should go into the file. About the success it is a response from the server which indicates if the request failed or not and I could have missed to implement that into the txt file.

Could you show a snippet of the outputted text file?

**Comment by FredrikM97** [comment]
This should now be solved in the latest files. If you download the latest version you can now decide how to log the data.
